# Generated by Django 3.2.5 on 2022-08-31 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(choices=[('SITRC', 'Sandip Institute Of Technology And Research Centre'), ('SIEM', 'Sandip Institute Of Engineering And Management'), ('SU', 'Sandip University')], default='SITRC', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='one-off-default@comp.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='', help_text='Without dial code.', max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='Only digits are allowed.', regex='^\\d*$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='college',
            field=models.CharField(choices=[('SITRC', 'Sandip Institute Of Technology And Research Centre'), ('SIEM', 'Sandip Institute Of Engineering And Management'), ('SU', 'Sandip University')], default='SITRC', max_length=5),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='email',
            field=models.EmailField(default='one-off-default@comp.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='full_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='phone',
            field=models.CharField(default='', help_text='Without dial code.', max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='Only digits are allowed.', regex='^\\d*$')]),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('college', 'standard', 'branch', 'division', 'roll_no')},
        ),
    ]
