# Generated by Django 3.2.5 on 2022-09-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_student_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='division',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='studentrequest',
            name='division',
        ),
        migrations.RemoveField(
            model_name='studentrequest',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='teacherrequest',
            name='division',
        ),
        migrations.AddField(
            model_name='student',
            name='prn',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='prn',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='college',
            field=models.CharField(choices=[('SITRC', 'Sandip Institute Of Technology And Research Centre'), ('SIEM', 'Sandip Institute Of Engineering And Management'), ('SU', 'Sandip University')], default='SITRC', max_length=5),
        ),
        migrations.AddField(
            model_name='teacherrequest',
            name='college',
            field=models.CharField(choices=[('SITRC', 'Sandip Institute Of Technology And Research Centre'), ('SIEM', 'Sandip Institute Of Engineering And Management'), ('SU', 'Sandip University')], default='SITRC', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='division',
        ),
    ]
