# Generated by Django 3.2.5 on 2022-09-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220904_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='teacherrequest',
            name='standard',
        ),
    ]
