# Generated by Django 3.2.5 on 2022-08-31 17:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_exam_show_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 17, 9, 36, 230780, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 17, 9, 49, 455193, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
